name: compile_cygwin

on: [push]

jobs:
  setup_cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login --norc -o igncr '{0}'

        
    steps:
      - name: setup_cygwin
        uses: cygwin/cygwin-install-action@v4
        with:
          platform: x86_64
          packages: mingw64-i686-gcc-core mingw64-i686-gcc-g++ mingw64-i686-headers mingw64-i686-runtime make wget unzip
      - name: Download_extract_clisp
        run: |
             wget https://gitlab.com/gnu-clisp/clisp/-/archive/master/clisp-master.zip
             unzip clisp-master.zip
      - name: configure
        run: |
             PATH=/usr/local/mingw32/bin:/usr/i686-w64-mingw32/sys-root/mingw/bin:$PATH
             export PATH
             pwd
             cd clisp-master
             ./configure --host=i686-w64-mingw32 --ignore-absence-of-libsigsegv --prefix=/usr/local/mingw32 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ CPPFLAGS="-I/usr/local/mingw32/include -Wall" LDFLAGS="-L/usr/local/mingw32/lib"
      - name: compile
        run: |
             make

