name: compile_cygwin

on: [push]

jobs:
  setup_cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        
    steps:
      - name: setup_cygwin
        uses: cygwin/cygwin-install-action@v4
        with:
          platform: x86_64
          packages: mingw64-i686-gcc-core mingw64-i686-gcc-g++ mingw64-i686-headers mingw64-i686-runtime make
      - name: Checkout_git
        uses: actions/checkout@v3
        with:
          repository: 'daute/clisp-mirror'
      - name: configure
        run: |
             cd clisp-mirror
             PATH=/usr/local/mingw32/bin:/usr/i686-w64-mingw32/sys-root/mingw/bin:$PATH
             export PATH
             ./configure --host=i686-w64-mingw32 --enable-portability --ignore-absence-of-libsigsegv --disable-threads
      - name: compile
        run: |
             cd clisp/build
             make
