name: compile_cygwin

on: [push]

jobs:
  setup_cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login --norc -o igncr '{0}'

        
    steps:
      - name: setup_cygwin
        uses: cygwin/cygwin-install-action@v4
        with:
          platform: x86_64
          packages: mingw64-i686-gcc-core mingw64-i686-gcc-g++ mingw64-i686-headers mingw64-i686-runtime make wget unzip patch
      - name: Download_libffcall
        run: wget https://ftp.gnu.org/gnu/libffcall/libffcall-2.4.tar.gz
      - name: Extract_libffcall
        run: tar xvf libffcall-2.4.tar.gz
      - name: Build_libffcall
        run: |
             cd libffcall-2.4
             bash ./configure --enable-static --enable-shared=no --build=i686-unknown-cygwin --host=i686-w64-mingw32 --prefix=/home/runneradmin/libffcall
             make
             make install
      - name: Download_libsigsegv
        run: wget https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.14.tar.gz
      - name: Extract_libffcall
        run: tar xvf libsigsegv-2.14.tar.gz
      - name: Build_libsigsegv
        run: |
             cd libsigsegv-2.14
             bash ./configure --build=i686-unknown-cygwin --host=i686-w64-mingw32 --prefix=/home/runneradmin/libsigsegv
             make
             make install
      - name: Download_extract_clisp
        run: |
             wget https://gitlab.com/gnu-clisp/clisp/-/archive/master/clisp-master.zip
             unzip clisp-master.zip
      - name: configure_clisp
        run: |
             PATH=/usr/local/mingw32/bin:/usr/i686-w64-mingw32/sys-root/mingw/bin:$PATH
             export PATH
             pwd
             cd clisp-master
             patch -p1 <../token-eof-patch
             bash ./configure --config --host=i686-w64-mingw32 --with-debug --disable-threads --enable-compatibility --with-libffcall-prefix=/home/runneradmin/libffcall --with-libsigsegv-prefix=/home/runneradmin/libsigsegv build
      - name: compile_clisp
        run: |
             pwd
             cd clisp-master/build
             make

