name: compile_cygwin

on: [push]

jobs:
  setup_cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login --norc -o igncr '{0}'

        
    steps:
      - name: setup_cygwin
        uses: cygwin/cygwin-install-action@v4
        with:
          platform: x86_64
          packages: mingw64-i686-gcc-core mingw64-i686-gcc-g++ mingw64-i686-headers mingw64-i686-runtime make
      - name: Prepare_git
        run: |
             git config --global core.autocrlf false
      - name: Checkout_git
        uses: actions/checkout@v3
        with:
          repository: 'daute/clisp-mirror'
      - name: configure
        run: |
             PATH=/usr/local/mingw32/bin:/usr/i686-w64-mingw32/sys-root/mingw/bin:$PATH
             export PATH
             pwd
             ls
             cd /cygdrive/d/a/clisp-crossbuild/clisp-crossbuild
             ls
             sed -r -i 's/\r//' configure */configure */*/configure src/build-aux/* *
             ./configure --host=i686-w64-mingw32 --ignore-absence-of-libsigsegv --prefix=/usr/local/mingw32 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ CPPFLAGS="-I/usr/local/mingw32/include -Wall" LDFLAGS="-L/usr/local/mingw32/lib"
      - name: compile
        run: |
             make

